// Copyright (c) 2026 Rami Al-Dhafiri.
// SPDX-License-Identifier: MIT

#include "nmc_pointer.h"

#include <dlfcn.h>
#include <gtk/gtk.h>

// X11 backend support for warpPointer.
//
// We do NOT link libX11 at build time. Doing so drags the system libX11 onto the
// final executable's link line, and on snap-packaged Flutter the old bundled
// toolchain (Clang 10 / old GLIBC) can't resolve the newer GLIBC symbols a
// modern system libX11 references (dlopen@GLIBC_2.34, __isoc23_strtol@2.38, …)
// → an undefined-reference link error in the host app.
//
// Instead we resolve XWarpPointer at RUNTIME via dlsym: when the app runs on an
// X11 session, GDK's X11 backend has already loaded libX11 into the process, so
// dlsym(RTLD_DEFAULT, "XWarpPointer") finds it with zero build-time linkage and
// no GLIBC coupling. GDK's gdk/gdkx.h still gives us GDK_IS_X11_DISPLAY /
// GDK_DISPLAY_XDISPLAY (header-only macros; their symbols are in the GTK lib we
// already link). On Wayland (or a build without the X11 GDK backend) the path is
// compiled/short-circuited out and warpPointer reports unsupported.
#ifdef GDK_WINDOWING_X11
#include <gdk/gdkx.h>
#define NMC_X11_RUNTIME 1
#endif

// Wayland infinite-drag support. Wayland forbids absolute pointer warping, but
// pointer-constraints-v1 (lock the pointer) + relative-pointer-v1 (keep getting
// relative deltas while locked) give the SAME effect as the web's Pointer Lock:
// an unbounded relative-motion stream with no edges. We expose it through the
// same lockPointer / unlockPointer / drainPointerLockDelta surface the web uses,
// so the Dart InfiniteDragController treats Wayland exactly like the web.
//
// Like the X11 path, we DON'T link libwayland-client (snap-toolchain GLIBC
// trap); we resolve the handful of wl_proxy_* core functions and the GDK-Wayland
// accessors at RUNTIME via dlsym (GDK already loaded both on a Wayland session).
// NMC_WAYLAND_HAVE_PROTOCOLS is defined by CMake when wayland-scanner produced
// the protocol glue (correct wl_interface tables) and we're on a Wayland-capable
// GTK. Only then do we compile the lock-pointer path.
#if defined(GDK_WINDOWING_WAYLAND) && defined(NMC_WAYLAND_HAVE_PROTOCOLS)
#include <gdk/gdkwayland.h>
#include <wayland-client-core.h>
#include <wayland-client-protocol.h>
// Generated by wayland-scanner from the system wayland-protocols XML (build dir
// on the include path). Provide the real interface descriptors + opcodes/enums.
#include "pointer-constraints-unstable-v1-client-protocol.h"
#include "relative-pointer-unstable-v1-client-protocol.h"
#define NMC_WAYLAND_RUNTIME 1
#endif

#include <cstdint>
#include <cstring>

// Per-plugin pointer state. Holds the borrowed registrar (to reach the
// GdkWindow) and, on Wayland, the bound managers + per-lock proxies + the
// accumulated relative motion.
struct _NmcPointer {
  FlPluginRegistrar* registrar;  // borrowed

  void* wl_constraints;       // zwp_pointer_constraints_v1* (bound ONCE, cached)
  void* wl_rel_manager;       // zwp_relative_pointer_manager_v1* (bound once)
  bool wl_bind_tried;         // we attempted to bind the managers already
  void* wl_locked_pointer;    // zwp_locked_pointer_v1* (per-lock)
  void* wl_relative_pointer;  // zwp_relative_pointer_v1* (per-lock)
  double wl_rel_dx;           // accumulated relative motion (logical px)
  double wl_rel_dy;
};

static double value_to_double(FlValue* v, double fallback) {
  if (v == nullptr) return fallback;
  switch (fl_value_get_type(v)) {
    case FL_VALUE_TYPE_INT:
      return static_cast<double>(fl_value_get_int(v));
    case FL_VALUE_TYPE_FLOAT:
      return fl_value_get_float(v);
    default:
      return fallback;
  }
}

static GdkWindow* get_gdk_window(NmcPointer* self) {
  if (self->registrar == nullptr) return nullptr;
  FlView* view = fl_plugin_registrar_get_view(self->registrar);
  if (view == nullptr) return nullptr;
  GtkWidget* toplevel = gtk_widget_get_toplevel(GTK_WIDGET(view));
  return gtk_widget_get_window(toplevel);
}

// ───────────────────────────────── X11 warp ─────────────────────────────────
#ifdef NMC_X11_RUNTIME
// XWarpPointer / XFlush resolved at runtime via dlsym (libX11 is already loaded
// by GDK's X11 backend on an X11 session). Signatures match Xlib's; we use
// XID/Display* from gdk/gdkx.h (which pulls in Xlib's types) so no extra link.
typedef int (*XWarpPointerFn)(Display*, ::Window, ::Window, int, int, unsigned,
                              unsigned, int, int);
typedef int (*XFlushFn)(Display*);

static XWarpPointerFn nmc_x_warp() {
  static XWarpPointerFn fn =
      reinterpret_cast<XWarpPointerFn>(dlsym(RTLD_DEFAULT, "XWarpPointer"));
  return fn;
}
static XFlushFn nmc_x_flush() {
  static XFlushFn fn =
      reinterpret_cast<XFlushFn>(dlsym(RTLD_DEFAULT, "XFlush"));
  return fn;
}
#endif

FlMethodResponse* nmc_pointer_can_warp(NmcPointer* self) {
  bool ok = false;
#ifdef NMC_X11_RUNTIME
  GdkDisplay* display = gdk_display_get_default();
  if (display != nullptr && GDK_IS_X11_DISPLAY(display) &&
      nmc_x_warp() != nullptr) {
    ok = true;
  }
#endif
  (void)self;
  return FL_METHOD_RESPONSE(
      fl_method_success_response_new(fl_value_new_bool(ok)));
}

FlMethodResponse* nmc_pointer_warp(NmcPointer* self, FlValue* args) {
#ifdef NMC_X11_RUNTIME
  GdkDisplay* display = gdk_display_get_default();
  XWarpPointerFn warp = nmc_x_warp();
  FlView* view = self->registrar
                     ? fl_plugin_registrar_get_view(self->registrar)
                     : nullptr;
  if (display != nullptr && GDK_IS_X11_DISPLAY(display) && warp != nullptr &&
      view != nullptr) {
    double lx = value_to_double(fl_value_lookup_string(args, "x"), 0);
    double ly = value_to_double(fl_value_lookup_string(args, "y"), 0);
    GdkWindow* window = gtk_widget_get_window(GTK_WIDGET(view));
    if (window != nullptr) {
      // x/y are Flutter-LOGICAL coords relative to the FlView (top-left,
      // y-down). Map to root (screen) X11 pixels. We anchor on the FlVIEW's own
      // window origin — NOT the toplevel's — because the toplevel origin can be
      // offset by window decorations / a header bar, which made the warp land
      // wrong vertically ("jump to top"). If the view shares the toplevel's
      // window (no native subwindow), add the view's allocation offset so (0,0)
      // still maps to the view's top-left.
      gint scale = gdk_window_get_scale_factor(window);
      gint ox = 0, oy = 0;
      gdk_window_get_origin(window, &ox, &oy);
      GtkAllocation alloc = {};
      gtk_widget_get_allocation(GTK_WIDGET(view), &alloc);
      if (!gtk_widget_get_has_window(GTK_WIDGET(view))) {
        ox += alloc.x * scale;
        oy += alloc.y * scale;
      }
      Display* xdisplay = GDK_DISPLAY_XDISPLAY(display);
      ::Window root = DefaultRootWindow(xdisplay);
      int rx = ox + static_cast<int>(lx * scale + 0.5);
      int ry = oy + static_cast<int>(ly * scale + 0.5);
      warp(xdisplay, None, root, 0, 0, 0, 0, rx, ry);
      if (XFlushFn flush = nmc_x_flush()) flush(xdisplay);
    }
  }
#endif
  (void)self;
  (void)args;
  return FL_METHOD_RESPONSE(fl_method_success_response_new(nullptr));
}

// ───────────────────────────── Wayland lock pointer ─────────────────────────
#ifdef NMC_WAYLAND_RUNTIME

// Older libwayland headers (pre-1.19) don't define WL_MARSHAL_FLAG_DESTROY,
// which wl_proxy_marshal_flags uses to also destroy the proxy. Its value is
// stable (bit 0); define it if absent.
#ifndef WL_MARSHAL_FLAG_DESTROY
#define WL_MARSHAL_FLAG_DESTROY (1u << 0)
#endif

// ---- runtime-resolved libwayland-client core (already loaded by GDK) --------
namespace nmc_wl {

// wl_proxy_marshal_flags — modern (libwayland ≥ 1.19.91): does both "create a
// new object" and "destroy" via flags.
typedef struct wl_proxy* (*marshal_flags_fn)(struct wl_proxy*, uint32_t,
                                             const struct wl_interface*,
                                             uint32_t, uint32_t, ...);
// Older (libwayland ≥ 1.9.91, present on 1.18): a constructor variant + a plain
// marshal + an explicit destroy. We use these when marshal_flags is absent.
typedef struct wl_proxy* (*marshal_constructor_fn)(struct wl_proxy*, uint32_t,
                                                   const struct wl_interface*,
                                                   ...);
typedef struct wl_proxy* (*marshal_constructor_versioned_fn)(
    struct wl_proxy*, uint32_t, const struct wl_interface*, uint32_t, ...);
typedef void (*marshal_fn)(struct wl_proxy*, uint32_t, ...);
typedef int (*add_listener_fn)(struct wl_proxy*, void (**)(void), void*);
typedef void (*proxy_destroy_fn)(struct wl_proxy*);
typedef uint32_t (*get_version_fn)(struct wl_proxy*);
typedef int (*display_roundtrip_fn)(struct wl_display*);
typedef int (*display_flush_fn)(struct wl_display*);

// A handle to libwayland-client. We prefer dlsym(RTLD_DEFAULT) (it works when
// the lib is in the global symbol scope, e.g. linked by GDK), but on
// snap-packaged Flutter GDK may load libwayland with RTLD_LOCAL / inside a
// loader namespace, so its symbols are NOT visible via RTLD_DEFAULT and every
// lookup returns null. As a fallback we explicitly open the already-loaded
// library by soname and dlsym from THAT handle. RTLD_NOLOAD grabs the in-process
// copy without loading a second one; if that misses we open it normally.
static void* wl_handle() {
  static void* h = [] {
    void* x = dlopen("libwayland-client.so.0", RTLD_NOW | RTLD_NOLOAD);
    if (x == nullptr) x = dlopen("libwayland-client.so.0", RTLD_NOW);
    if (x == nullptr) x = dlopen("libwayland-client.so", RTLD_NOW);
    return x;
  }();
  return h;
}

template <typename T>
static T sym(const char* name) {
  // Try the global scope first, then the explicit libwayland-client handle.
  void* p = dlsym(RTLD_DEFAULT, name);
  if (p == nullptr && wl_handle() != nullptr) p = dlsym(wl_handle(), name);
  return reinterpret_cast<T>(p);
}

static marshal_flags_fn marshal_flags() {
  static auto f = sym<marshal_flags_fn>("wl_proxy_marshal_flags");
  return f;
}
static marshal_constructor_fn marshal_constructor() {
  static auto f = sym<marshal_constructor_fn>("wl_proxy_marshal_constructor");
  return f;
}
static marshal_constructor_versioned_fn marshal_constructor_versioned() {
  static auto f = sym<marshal_constructor_versioned_fn>(
      "wl_proxy_marshal_constructor_versioned");
  return f;
}
static marshal_fn marshal() {
  static auto f = sym<marshal_fn>("wl_proxy_marshal");
  return f;
}
static add_listener_fn add_listener() {
  static auto f = sym<add_listener_fn>("wl_proxy_add_listener");
  return f;
}
static proxy_destroy_fn proxy_destroy() {
  static auto f = sym<proxy_destroy_fn>("wl_proxy_destroy");
  return f;
}
static get_version_fn get_version() {
  static auto f = sym<get_version_fn>("wl_proxy_get_version");
  return f;
}
static display_roundtrip_fn roundtrip() {
  static auto f = sym<display_roundtrip_fn>("wl_display_roundtrip");
  return f;
}
static display_flush_fn flush() {
  static auto f = sym<display_flush_fn>("wl_display_flush");
  return f;
}

// The wl_registry_interface descriptor (exported by libwayland-client), needed
// to construct a registry. Resolved via the same global-then-handle dance.
static const struct wl_interface* registry_iface() {
  void* p = dlsym(RTLD_DEFAULT, "wl_registry_interface");
  if (p == nullptr && wl_handle() != nullptr) {
    p = dlsym(wl_handle(), "wl_registry_interface");
  }
  return reinterpret_cast<const struct wl_interface*>(p);
}

// wl_display_get_registry is NOT an exported symbol — it's a static inline in
// the header that calls wl_proxy_marshal_constructor(display, 1 /*GET_REGISTRY*/,
// &wl_registry_interface, NULL). So we can't dlsym it; we replicate it.
static struct wl_proxy* get_registry(struct wl_display* dpy) {
  const struct wl_interface* iface = registry_iface();
  if (iface == nullptr) return nullptr;
  auto* display_proxy = reinterpret_cast<struct wl_proxy*>(dpy);
  // WL_DISPLAY_GET_REGISTRY opcode = 1. Prefer the modern marshal_flags, else
  // the older constructor.
  if (marshal_flags()) {
    return marshal_flags()(display_proxy, 1, iface, get_version()(display_proxy),
                           0, nullptr);
  }
  if (marshal_constructor()) {
    return marshal_constructor()(display_proxy, 1, iface, nullptr);
  }
  return nullptr;
}

// Enough of the wl_proxy_* primitives present to drive the lock path? We need
// add_listener/destroy/version/roundtrip + the registry interface, PLUS at least
// one way to marshal a constructing request (modern marshal_flags OR the older
// marshal_constructor(_versioned)).
static bool core_ok() {
  const bool can_construct =
      marshal_flags() != nullptr ||
      marshal_constructor_versioned() != nullptr ||
      marshal_constructor() != nullptr;
  const bool can_destroy_req =
      marshal_flags() != nullptr || marshal() != nullptr;
  return can_construct && can_destroy_req && add_listener() && proxy_destroy() &&
         get_version() && roundtrip() && registry_iface() != nullptr;
}

// ---- request wrappers: modern marshal_flags OR the 1.18 constructor path ----

// wl_registry.bind(name, interface_name, version, new_id) — opcode 0.
static struct wl_proxy* registry_bind(struct wl_proxy* registry, uint32_t name,
                                      const struct wl_interface* iface,
                                      uint32_t version) {
  if (marshal_flags()) {
    return marshal_flags()(registry, 0, iface, version, 0, name, iface->name,
                           version, nullptr);
  }
  if (marshal_constructor_versioned()) {
    return marshal_constructor_versioned()(registry, 0, iface, version, name,
                                           iface->name, version, nullptr);
  }
  if (marshal_constructor()) {
    return marshal_constructor()(registry, 0, iface, name, iface->name, version,
                                 nullptr);
  }
  return nullptr;
}

// A constructing request with one wl_object arg: get_relative_pointer(new, ptr).
static struct wl_proxy* construct1(struct wl_proxy* proxy, uint32_t opcode,
                                   const struct wl_interface* new_iface,
                                   void* arg0) {
  if (marshal_flags()) {
    return marshal_flags()(proxy, opcode, new_iface, get_version()(proxy), 0,
                           nullptr, arg0);
  }
  if (marshal_constructor()) {
    return marshal_constructor()(proxy, opcode, new_iface, nullptr, arg0);
  }
  return nullptr;
}

// lock_pointer(new, surface, pointer, region=null, lifetime): 3 objs + 1 uint.
static struct wl_proxy* construct_lock(struct wl_proxy* proxy, uint32_t opcode,
                                       const struct wl_interface* new_iface,
                                       void* surface, void* pointer,
                                       void* region, uint32_t lifetime) {
  if (marshal_flags()) {
    return marshal_flags()(proxy, opcode, new_iface, get_version()(proxy), 0,
                           nullptr, surface, pointer, region, lifetime);
  }
  if (marshal_constructor()) {
    return marshal_constructor()(proxy, opcode, new_iface, nullptr, surface,
                                 pointer, region, lifetime);
  }
  return nullptr;
}

// A no-arg destructor request (opcode), then free the proxy.
static void destroy_request(struct wl_proxy* proxy, uint32_t opcode) {
  if (proxy == nullptr) return;
  if (marshal_flags()) {
    marshal_flags()(proxy, opcode, nullptr, get_version()(proxy),
                    WL_MARSHAL_FLAG_DESTROY);
    return;
  }
  if (marshal()) marshal()(proxy, opcode);
  if (proxy_destroy()) proxy_destroy()(proxy);
}

}  // namespace nmc_wl

// ---- relative_motion listener (typed via the generated header) --------------
// Accumulate the UNACCELERATED dx/dy. GNOME/Mutter's pointer-acceleration curve
// flattens SLOW movement toward zero, so the accelerated `dx` is ~0 for a
// controlled scrub (→ "can't change the value"). The unaccelerated delta is
// linear and preserves slow movement, which is what a scrub needs. wl_fixed_t is
// 24.8 fixed point → /256 for the logical value.
static void nmc_wl_relative_motion(void* data,
                                   struct zwp_relative_pointer_v1* /*relptr*/,
                                   uint32_t /*utime_hi*/, uint32_t /*utime_lo*/,
                                   wl_fixed_t /*dx*/, wl_fixed_t /*dy*/,
                                   wl_fixed_t dx_unaccel,
                                   wl_fixed_t dy_unaccel) {
  auto* self = static_cast<NmcPointer*>(data);
  self->wl_rel_dx += static_cast<double>(dx_unaccel) / 256.0;
  self->wl_rel_dy += static_cast<double>(dy_unaccel) / 256.0;
}

static const struct zwp_relative_pointer_v1_listener nmc_wl_relptr_listener = {
    nmc_wl_relative_motion};

// Registry listener to bind exactly one global by interface name.
namespace {
struct WlBindTarget {
  const char* want;
  uint32_t want_version;
  const struct wl_interface* iface;
  struct wl_proxy* registry;
  struct wl_proxy* result;
};

void nmc_wl_registry_global(void* data, struct wl_proxy* /*registry*/,
                            uint32_t name, const char* interface,
                            uint32_t version) {
  auto* t = static_cast<WlBindTarget*>(data);
  if (t->result != nullptr || strcmp(interface, t->want) != 0) return;
  uint32_t v = version < t->want_version ? version : t->want_version;
  t->result = nmc_wl::registry_bind(t->registry, name, t->iface, v);
}
void nmc_wl_registry_global_remove(void*, struct wl_proxy*, uint32_t) {}

// Non-const so it passes to wl_proxy_add_listener's void(**)(void) parameter
// without stripping const. (The Wayland API only reads it.)
void (*kRegistryListener[])(void) = {
    reinterpret_cast<void (*)(void)>(nmc_wl_registry_global),
    reinterpret_cast<void (*)(void)>(nmc_wl_registry_global_remove)};
}  // namespace

static bool nmc_wl_available(NmcPointer* self) {
  GdkDisplay* display = gdk_display_get_default();
  if (display == nullptr || !GDK_IS_WAYLAND_DISPLAY(display)) return false;
  return nmc_wl::core_ok() && get_gdk_window(self) != nullptr;
}

static struct wl_proxy* nmc_wl_bind(struct wl_display* dpy, const char* name,
                                    uint32_t version,
                                    const struct wl_interface* iface) {
  struct wl_proxy* registry = nmc_wl::get_registry(dpy);
  if (registry == nullptr) return nullptr;
  WlBindTarget target = {name, version, iface, registry, nullptr};
  nmc_wl::add_listener()(registry, kRegistryListener, &target);
  nmc_wl::roundtrip()(dpy);
  nmc_wl::proxy_destroy()(registry);
  return target.result;
}

#endif  // NMC_WAYLAND_RUNTIME

FlMethodResponse* nmc_pointer_lock(NmcPointer* self) {
  bool ok = false;
#ifdef NMC_WAYLAND_RUNTIME
  // If a previous lock wasn't released (e.g. a missed drag-end), tear it down
  // before starting a fresh one — never stack two relative pointers.
  if (self->wl_relative_pointer != nullptr ||
      self->wl_locked_pointer != nullptr) {
    g_autoptr(FlMethodResponse) discard = nmc_pointer_unlock(self);
    (void)discard;
  }
  if (nmc_wl_available(self)) {
    GdkDisplay* gdpy = gdk_display_get_default();
    struct wl_display* dpy = gdk_wayland_display_get_wl_display(gdpy);
    GdkWindow* win = get_gdk_window(self);
    struct wl_surface* surface =
        win ? gdk_wayland_window_get_wl_surface(win) : nullptr;
    GdkSeat* seat = gdk_display_get_default_seat(gdpy);
    GdkDevice* ptr = seat ? gdk_seat_get_pointer(seat) : nullptr;
    struct wl_pointer* wlptr =
        ptr ? gdk_wayland_device_get_wl_pointer(ptr) : nullptr;

    if (dpy && surface && wlptr) {
      // Bind the two MANAGERS exactly ONCE (they're long-lived globals) and
      // cache them. Rebinding them every lock — with a throwaway registry +
      // roundtrip on GDK's shared display each time — was racy: freed proxy IDs
      // got recycled across cycles and the new relative-pointer sometimes
      // received NO motion events (the drag "sticks"). Only the per-lock
      // locked_pointer + relative_pointer are created/destroyed each drag.
      if (!self->wl_bind_tried) {
        self->wl_bind_tried = true;
        self->wl_constraints =
            nmc_wl_bind(dpy, "zwp_pointer_constraints_v1", 1,
                        &zwp_pointer_constraints_v1_interface);
        self->wl_rel_manager =
            nmc_wl_bind(dpy, "zwp_relative_pointer_manager_v1", 1,
                        &zwp_relative_pointer_manager_v1_interface);
      }

      if (self->wl_constraints) {
        // lock_pointer(new_id, surface, pointer, region=null, lifetime).
        self->wl_locked_pointer = nmc_wl::construct_lock(
            static_cast<struct wl_proxy*>(self->wl_constraints),
            ZWP_POINTER_CONSTRAINTS_V1_LOCK_POINTER,
            &zwp_locked_pointer_v1_interface, surface, wlptr, nullptr,
            ZWP_POINTER_CONSTRAINTS_V1_LIFETIME_PERSISTENT);
      }
      if (self->wl_rel_manager) {
        // get_relative_pointer(new_id, pointer).
        struct wl_proxy* relptr = nmc_wl::construct1(
            static_cast<struct wl_proxy*>(self->wl_rel_manager),
            ZWP_RELATIVE_POINTER_MANAGER_V1_GET_RELATIVE_POINTER,
            &zwp_relative_pointer_v1_interface, wlptr);
        if (relptr) {
          self->wl_rel_dx = 0;
          self->wl_rel_dy = 0;
          nmc_wl::add_listener()(
              relptr,
              reinterpret_cast<void (**)(void)>(
                  const_cast<zwp_relative_pointer_v1_listener*>(
                      &nmc_wl_relptr_listener)),
              self);
          self->wl_relative_pointer = relptr;
        }
      }
      // Flush the lock_pointer + get_relative_pointer requests to the compositor
      // (send-only — don't roundtrip/dispatch, which would reenter GDK). GDK's
      // loop delivers the relative_motion events afterward.
      if (nmc_wl::flush()) nmc_wl::flush()(dpy);
      ok = self->wl_relative_pointer != nullptr;
    }
  }
#endif
  (void)self;
  return FL_METHOD_RESPONSE(
      fl_method_success_response_new(fl_value_new_bool(ok)));
}

FlMethodResponse* nmc_pointer_unlock(NmcPointer* self) {
#ifdef NMC_WAYLAND_RUNTIME
  if (self->wl_relative_pointer) {
    nmc_wl::destroy_request(
        static_cast<struct wl_proxy*>(self->wl_relative_pointer),
        ZWP_RELATIVE_POINTER_V1_DESTROY);
    self->wl_relative_pointer = nullptr;
  }
  if (self->wl_locked_pointer) {
    nmc_wl::destroy_request(
        static_cast<struct wl_proxy*>(self->wl_locked_pointer),
        ZWP_LOCKED_POINTER_V1_DESTROY);
    self->wl_locked_pointer = nullptr;
  }
  // Flush the destroy requests (send-only; GDK's loop handles the rest).
  GdkDisplay* gdpy = gdk_display_get_default();
  if (gdpy && GDK_IS_WAYLAND_DISPLAY(gdpy) && nmc_wl::flush()) {
    nmc_wl::flush()(gdk_wayland_display_get_wl_display(gdpy));
  }
  self->wl_rel_dx = 0;
  self->wl_rel_dy = 0;
#endif
  (void)self;
  return FL_METHOD_RESPONSE(fl_method_success_response_new(nullptr));
}

FlMethodResponse* nmc_pointer_drain(NmcPointer* self) {
  double out_dx = 0, out_dy = 0;
#ifdef NMC_WAYLAND_RUNTIME
  // Pump the Wayland connection so our relative_pointer events are dispatched
  // before we read the accumulator. GDK's main loop dispatches the default queue
  // too, but during a Flutter drag its dispatch of OUR custom proxy gets starved.
  // A roundtrip flushes our requests AND blocks for one server reply, draining +
  // dispatching all pending events — including our relative_motion. It's the
  // known-good pump; the brief block is fine for a 16 ms drag poll.
  GdkDisplay* gdpy = gdk_display_get_default();
  if (gdpy != nullptr && GDK_IS_WAYLAND_DISPLAY(gdpy) && nmc_wl::roundtrip()) {
    struct wl_display* dpy = gdk_wayland_display_get_wl_display(gdpy);
    if (dpy != nullptr) nmc_wl::roundtrip()(dpy);
  }
  // The relative-motion deltas are in PHYSICAL device px, but the controller /
  // app scrub is tuned for LOGICAL px (Flutter's d.delta / globalPosition, which
  // the warp platforms use). On a HiDPI display (scale 2) the raw delta is ~2×
  // too large → the value races. Divide by the window's scale factor so the feel
  // matches macOS/Windows/X11.
  GdkWindow* win = get_gdk_window(self);
  double scale =
      win ? static_cast<double>(gdk_window_get_scale_factor(win)) : 1.0;
  if (scale < 1.0) scale = 1.0;
  out_dx = self->wl_rel_dx / scale;
  out_dy = self->wl_rel_dy / scale;
  self->wl_rel_dx = 0;
  self->wl_rel_dy = 0;
#endif
  (void)self;
  FlValue* out = fl_value_new_map();
  fl_value_set_string_take(out, "dx", fl_value_new_float(out_dx));
  fl_value_set_string_take(out, "dy", fl_value_new_float(out_dy));
  return FL_METHOD_RESPONSE(fl_method_success_response_new(out));
}

// ─────────────────────────────── lifecycle ──────────────────────────────────

NmcPointer* nmc_pointer_new(FlPluginRegistrar* registrar) {
  NmcPointer* p = g_new0(NmcPointer, 1);
  p->registrar = registrar;
  return p;
}

void nmc_pointer_free(NmcPointer* self) {
  if (self == nullptr) return;
#ifdef NMC_WAYLAND_RUNTIME
  // Release the Wayland proxies (per-lock + cached managers). Guarded so
  // non-Wayland builds skip it.
  if (nmc_wl::proxy_destroy()) {
    if (self->wl_relative_pointer) {
      nmc_wl::proxy_destroy()(
          static_cast<struct wl_proxy*>(self->wl_relative_pointer));
    }
    if (self->wl_locked_pointer) {
      nmc_wl::proxy_destroy()(
          static_cast<struct wl_proxy*>(self->wl_locked_pointer));
    }
    if (self->wl_rel_manager) {
      nmc_wl::proxy_destroy()(
          static_cast<struct wl_proxy*>(self->wl_rel_manager));
    }
    if (self->wl_constraints) {
      nmc_wl::proxy_destroy()(
          static_cast<struct wl_proxy*>(self->wl_constraints));
    }
  }
#endif
  g_free(self);
}
